//
//  Dogs.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class Dogs: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _dogID: String?
    var _age: NSNumber?
    var _breed: String?
    var _gender: String?
    var _name: String?
    var _spayedNeutered: NSNumber?
    var _weight: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "pawsy-mobilehub-1849707752-Dogs"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_dogID"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_dogID" : "dogID",
               "_age" : "age",
               "_breed" : "breed",
               "_gender" : "gender",
               "_name" : "name",
               "_spayedNeutered" : "spayed/neutered",
               "_weight" : "weight",
        ]
    }
}
