// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:752bf65c-1e18-489b-8892-b77f914cfd7c',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'pawsy-hosting-mobilehub-762370709',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd16o8ehgvd9rvu.cloudfront.net',
    'aws_mobile_analytics_app_id': 'f61332d388a14f6b963bf7d10496a3ea',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'a4ead88b-2875-40a3-862d-8409ffe9e011',
    'aws_project_name': 'Pawsy-2018-01-17-21-07-57',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'pawsy-mobilehub-762370709',
}

export default awsmobile;
