// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:055ef770-bdd2-4011-8641-3f07cbcebfb0',
    'aws_cognito_region': 'us-east-1',
    'aws_mobile_analytics_app_id': '57f1a5f871fb444ab4fa99266a503649',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '9061872b-e199-4ebb-8e36-c4fb3bf13273',
    'aws_project_name': 'Pawsy',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'pawsy-mobilehub-1849707752',
}

export default awsmobile;
